Repository qooxdoo/qooxdoo, pull requests merged in 2019-07, with the labels that each got.

#9726 new url for version image
  README.md
Labels: C:documentation

#9727 Publish docs and apps on website
  .gitignore
  .travis/build-site-v6
  .travis/deploy
  apps/.npmignore
Labels: C:documentation

#9728 Replace xml-based variable file with json-based one
  docs/_media/docsify-variables.min.js
  docs/_variables.json
  docs/_variables.xml
  docs/index.html
  tool/admin/bin/bumpqxversion.py
Labels: C:documentation

#9731 This fixes (& speeds up) the "deploy" step in our travis integration
  .travis.yml
  .travis/build-site
  .travis/check-github-label
  .travis/coverage
  .travis/deploy_website
  .travis/test
Labels: ci-skip-browser-tests, hotfix

#9732 Fixes a wrong path in .travis.yml
  .travis.yml
  .travis/build-site-v6
  .travis/check-github-label
Labels: ci-skip-browser-tests, hotfix

#9733 More travis optimizations
  .travis.yml
  .travis/build-site-v6
  .travis/check-github-label
  .travis/coverage
  .travis/test
  apps/.npmignore
  docs/about.md
Labels: ci-skip-browser-tests, enhancement

#9738 Do not fail with error if no label is found
  .travis.yml
Labels: blocker, bug, hotfix

#9734 fix address
  docs/about.md
Labels: C:documentation

#9741 fix travis
  .travis.yml
Labels: hotfix

#9742 Add mobileshowcase
  .travis/build-site-v6
  compile.json
  docs/apps.md
  qx-lock.json
Labels: C:documentation, enhancement

#9737 fix sendWithPromise() doesn't send
  framework/source/class/qx/io/request/AbstractRequest.js
  framework/source/class/qx/test/io/request/Xhr.js
Labels: bug

#9749 disable Firefox SL test because SL hangs
  .travis.yml
Labels: hotfix

#9750 fix syntax
  .travis/build-site-v6
Labels: hotfix

#9746 make this compileable by qx
  framework/source/class/qx/module/Blocker.js
  framework/source/class/qx/module/Placement.js
Labels: bug

#9747 Fix for #9743
  framework/source/class/qx/ui/layout/VBox.js
Labels: bug

#9751 To load mobile widget correct we need a @require(qx.bom.Lifecycle)
  framework/source/class/qx/ui/mobile/core/Widget.js
Labels: bug

#9757 Make /docs link to current master documentation
  .travis/deploy_website
Labels: hotfix

#9758 added docs to match https://github.com/qooxdoo/qooxdoo-compiler/pull/…
  docs/compiler/Sass.md
Labels: C:documentation.api

#9760 Fix failed attempt to add symlink to current docs
  .travis/deploy_website
Labels: hotfix

#9759 some more fixes to make the compiler happy
  compile.json
  compileServer.json
  framework/source/class/qx/dev/unit/Sinon.js
  framework/source/class/qx/ui/mobile/container/Carousel.js
Labels: C:tool.generator.compiler

#9761 Fix broken website deployment, this also fixes npm vulnerabilities
  .travis/deploy_website
  package-lock.json
Labels: hotfix

#9762 link to doc path is wrong
  .travis/deploy_website
Labels: hotfix
