Repository qooxdoo/qooxdoo, pull requests merged in 2019-10, with the labels that each got.

#9797 fix regression causing circular load time dependency
  framework/source/class/qx/Bootstrap.js
  framework/source/class/qx/Class.js
  framework/source/class/qx/log/Logger.js
Labels: blocker, bug, critical, hotfix

#9800 fixes a bug with mixins when added via `qx.Class.patch`
  framework/source/class/qx/Class.js
  framework/source/class/qx/test/Mixin.js
  framework/source/class/qx/test/testclasses/BaseClassBoth.js
  framework/source/class/qx/test/testclasses/BaseClassIncluded.js
  framework/source/class/qx/test/testclasses/BaseClassPatched.js
  framework/source/class/qx/test/testclasses/DerivedClassBoth.js
  framework/source/class/qx/test/testclasses/DerivedClassIncluded.js
  framework/source/class/qx/test/testclasses/DerivedClassPatched.js
  framework/source/class/qx/test/testclasses/MMixinOne.js
  framework/source/class/qx/test/testclasses/MMixinTwo.js
  framework/source/class/qx/test/testclasses/RootClass.js
Labels: donotmerge

#9803 build schema doc from schema file during building of site.
  .travis/build-site-v6
  docs/compiler/configuration/compile-1-0-0.md
  docs/compiler/configuration/compile.md
Labels: C:documentation
