Repository qooxdoo/qooxdoo, pull requests merged in 2019-06, with the labels that each got.

#9697 Lint markdown files and skip tests if only markdown files have been committed
  .travis.yml
  .travis/check-if-docs-only
  .travis/markdown-lint
  README.md
Labels: bug

#9695 use always the newest qooxdoo compiler to compile framework
  .travis/deploy_npm
Labels: bug

#9275 Fix problem with initially attached Commands
  framework/source/class/qx/test/ui/command/Command.js
  framework/source/class/qx/ui/core/MExecutable.js
  framework/source/class/qx/ui/core/Widget.js
Labels: VOTING, blocker, bug

#9701 [travis-docs-only] adds documentation for https://github.com/qooxdoo/qooxdoo-compiler/pull/448
  docs/_sidebar.md
  docs/configuration/api.md
  docs/configuration/compile.md
  docs/configuration/overview.md
Labels: C:documentation

#9703 let index.html show to qooxdoo repos
  docs/index.html
Labels: C:documentation

#9714 fixes app build
  .travis/deploy_npm
  Manifest.json
Labels: hotfix

#9716 second try to fix deployment
  .travis/deploy_npm
Labels: hotfix

#9720 next try to fix deployment
  .travis/deploy_npm
  apps/.npmignore
  apps/demobrowser/script/.npmignore
Labels: hotfix

#9718 Lower the approval quorum for all markdown files regardless of in which folder they live
  .pullapprove.yml
Labels: C:documentation.api

#9717 fix links in readme.md
  README.md
Labels: C:documentation

#9721 fix deploy to npm 4 - update to node 11
  .travis/deploy_npm
Labels: hotfix

#9715 Update qooxdoo NPM package name
  README.md
Labels: C:documentation.api

#9722 fixes tutorial - it should not be necessary to specify the framework,…
  docs/tutorial/twitter/tutorial-part-1.md
Labels: C:documentation

#9723 fix deploy to npm
  .travis/deploy_npm
  .travis/prepare_npm
  package-lock.json
  package.json
  qx-lock.json
Labels: hotfix
