Repository qooxdoo/qooxdoo, pull requests merged in 2021-11, with the labels that each got.

#10278 we should return a valid href here
  source/resource/qx/tool/cli/templates/loader/loader-node.tmpl.js
Labels: backport candidate for compiler 1.0

#10277 Adds more accessibility support by adding some ARIA attrs
  docs/release-notes.md
  source/class/qx/ui/container/SlideBar.js
  source/class/qx/ui/core/scroll/NativeScrollBar.js
  source/class/qx/ui/core/scroll/ScrollBar.js
  source/class/qx/ui/form/AbstractSelectBox.js
  source/class/qx/ui/form/Button.js
  source/class/qx/ui/form/CheckBox.js
  source/class/qx/ui/form/ComboBox.js
  source/class/qx/ui/form/List.js
  source/class/qx/ui/form/MenuButton.js
  source/class/qx/ui/form/RadioButton.js
  source/class/qx/ui/form/RadioButtonGroup.js
  source/class/qx/ui/form/SelectBox.js
  source/class/qx/ui/form/Slider.js
  source/class/qx/ui/form/SplitButton.js
  source/class/qx/ui/form/ToggleButton.js
  source/class/qx/ui/menu/AbstractButton.js
  source/class/qx/ui/menu/Button.js
  source/class/qx/ui/menu/CheckBox.js
  source/class/qx/ui/menu/Menu.js
  source/class/qx/ui/menu/RadioButton.js
  source/class/qx/ui/menubar/Button.js
  source/class/qx/ui/menubar/MenuBar.js
  source/class/qx/ui/splitpane/Blocker.js
  source/class/qx/ui/splitpane/Pane.js
  source/class/qx/ui/table/Table.js
  source/class/qx/ui/table/cellrenderer/Abstract.js
  source/class/qx/ui/table/cellrenderer/AbstractImage.js
  source/class/qx/ui/table/headerrenderer/HeaderCell.js
  source/class/qx/ui/table/pane/Header.js
  source/class/qx/ui/table/rowrenderer/Default.js
  source/class/qx/ui/tabview/Page.js
  source/class/qx/ui/tabview/TabView.js
  source/class/qx/ui/toolbar/RadioButton.js
  source/class/qx/ui/toolbar/ToolBar.js
Labels: backport candidate for qx 6.0

#10287 Fix require
  compile.js
Labels: hotfix
